name: Upload Workflow
inputs:
  platform:
    required: true
    description: "Current platform"
  AWS_KEY:
    required: true
    description: "AWS KEY"
  AWS_SECRET_KEY:
    required: true
    description: "AWS SECRET KEY"
  AWS_BUCKET:
    required: true
    description: "AWS BUCKET NAME"
  project-name:
    required: true
    description: "Project name"
  client-name:
    required: true
    description: "Client name"
  version:
      required: true
      description: "Build version"

# outputs:
#   random:
#     description: "Example output"
#     value: ${{ steps.step1.outputs.random }}

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Download Webgl Artifact
      uses: actions/download-artifact@v4
      with:
        name: build-${{ inputs.platform }}
        path: build-${{ inputs.platform }}-extract
    - name: Zip artifact
      run: |
        zip -r build-${{ inputs.platform }}.zip build-${{ inputs.platform }}-extract
      shell: bash
    - name: Upload Directory to S3
      run: |
        aws s3 sync ./build-${{ inputs.platform }}-extract/ s3://${{inputs.AWS_BUCKET}}/${{inputs.client-name}}/${{ inputs.project-name }}/
      env:
        AWS_ACCESS_KEY_ID: ${{inputs.AWS_KEY}}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: 'eu-west-3'
      shell: bash 
    - name: Upload Zip to S3
      run: |
        aws s3 cp ./build-${{ inputs.platform }}.zip s3://${{inputs.AWS_BUCKET}}/${{inputs.client-name}}/${{ inputs.project-name }}/build-${{ inputs.platform }}.zip
      env:
        AWS_ACCESS_KEY_ID: ${{inputs.AWS_KEY}}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: 'eu-west-3'
      shell: bash