name: Upload Workflow
inputs:
  platform:
    required: true
    description: "Current platform"
  version:
    required: true
    description: "Current version" 
  AWS_KEY:
    required: true
    description: "AWS KEY"
  AWS_SECRET_KEY:
    required: true
    description: "AWS SECRET KEY"
  AWS_BUCKET:
    required: true
    description: "AWS BUCKET NAME"
  project-name:
    required: true
    description: "Project name"
  client-name:
    required: true
    description: "Client name"
  GITHUB_TOKEN:
    required: true
    description: "Github token"

# outputs:
#   random:
#     description: "Example output"
#     value: ${{ steps.step1.outputs.random }}

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Download Webgl Artifact
      uses: actions/download-artifact@v4
      with:
        name: build-${{ inputs.platform }}
        path: build-${{ inputs.platform }}-${{inputs.version}}
    - name: Zip artifact
      run: |
        zip -r build-${{ inputs.platform }}-${{inputs.version}}.zip build-${{ inputs.platform }}-${{inputs.version}}
      shell: bash
    - name: Upload Directory to S3
      run: |
        aws s3 sync ./build-${{ inputs.platform }}-${{inputs.version}}/ s3://${{inputs.AWS_BUCKET}}/${{inputs.client-name}}/${{ inputs.project-name }}/${{inputs.version}}/
      env:
        AWS_ACCESS_KEY_ID: ${{inputs.AWS_KEY}}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: 'eu-west-3'
      shell: bash 
    - name: Upload Zip to S3
      run: |
        aws s3 cp ./build-${{ inputs.platform }}-${{inputs.version}}.zip s3://${{inputs.AWS_BUCKET}}/${{inputs.client-name}}/${{ inputs.project-name }}/${{inputs.version}}/build-${{ inputs.platform }}-${{inputs.version}}.zip
      env:
        AWS_ACCESS_KEY_ID: ${{inputs.AWS_KEY}}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_KEY }} 
        AWS_DEFAULT_REGION: 'eu-west-3'
      shell: bash
    - name: Build Changelog 
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v5
      with:
        mode: "COMMIT"
        configurationJson: |
          {
            "template": "#{{CHANGELOG}}",
            "categories": [
              {
                  "title": "## Feature",
                  "labels": ["feat", "feature"]
              },
              {
                  "title": "## Fix",
                  "labels": ["fix", "bug"]
              },
              {
                  "title": "## Other",
                  "labels": [perf, refactor, test, revert]
              }
            ],
            "ignore_labels": [chore, ignore],
            "label_extractor": [
              {
                "pattern": "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test|release|BREAKING CHANGE)(\(.*\))?: .*$",
                "on_property": "title",
                "method": "replace",
                "target": "$1"
              }
            ]
          }
      env:
        GITHUB_TOKEN: ${{inputs.GITHUB_TOKEN}}
    - name: Create a release
      uses: softprops/action-gh-release@v2
      with:
        body: ${{steps.github_release.outputs.changelog}}
        files: ./build-${{ inputs.platform }}-${{inputs.version}}.zip
        tag_name: ${{inputs.version}}
        name: ${{inputs.version}}


