name: Upload Workflow
inputs:
  platform:
    required: true
    description: "Current platform"
  AWS_KEY:
    required: true
    description: "AWS KEY"
  AWS_SECRET_KEY:
    required: true
    description: "AWS SECRET KEY"
  AWS_BUCKET:
    required: true
    description: "AWS BUCKET NAME"
  project-name:
    required: true
    description: "Project name"
  client-name:
    required: true
    description: "Client name"
  version:
    required: true
    description: "Build version"
  GITHUB_TOKEN:
    required: true
    description: "Github token"

# outputs:
#   random:
#     description: "Example output"
#     value: ${{ steps.step1.outputs.random }}

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Create version
      id: semantic
      uses: paulhatch/semantic-version@v5.0.2
      with:
        tag_prefix: "v"
        bump_each_commit: true
        major_pattern: "/BREAKING CHANGE:|release:/"
        minor_pattern:  "/feat:/"
        version_format: "${major}.${minor}.${patch}"
    - name: Set Version Tag
      id: version
      run: |
        git tag ${{steps.semantic.outputs.version_tag}} 
        git push origin ${{steps.semantic.outputs.version_tag}}
      shell: bash
    - name: Print version
      run: |
        echo ${{steps.semantic.outputs.version_tag}}
      shell: bash
    - name: Download Webgl Artifact
      uses: actions/download-artifact@v4
      with:
        name: build-${{ inputs.platform }}
        path: build-${{ inputs.platform }}-${{steps.semantic.outputs.version_tag}}
    - name: Zip artifact
      run: |
        zip -r build-${{ inputs.platform }}-${{steps.semantic.outputs.version_tag}}.zip build-${{ inputs.platform }}-${{steps.semantic.outputs.version_tag}}
      shell: bash
    - name: Upload Directory to S3
      run: |
        aws s3 sync ./build-${{ inputs.platform }}-${{steps.semantic.outputs.version_tag}}/ s3://${{inputs.AWS_BUCKET}}/${{inputs.client-name}}/${{ inputs.project-name }}/${{steps.semantic.outputs.version_tag}}/
      env:
        AWS_ACCESS_KEY_ID: ${{inputs.AWS_KEY}}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: 'eu-west-3'
      shell: bash 
    - name: Upload Zip to S3
      run: |
        aws s3 cp ./build-${{ inputs.platform }}-${{steps.semantic.outputs.version_tag}}.zip s3://${{inputs.AWS_BUCKET}}/${{inputs.client-name}}/${{ inputs.project-name }}/${{steps.semantic.outputs.version_tag}}/build-${{ inputs.platform }}-${{steps.semantic.outputs.version_tag}}.zip
      env:
        AWS_ACCESS_KEY_ID: ${{inputs.AWS_KEY}}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: 'eu-west-3'
      shell: bash
    - name: Build Changelog 
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v5
      mode: "COMMIT"
      env:
        GITHUB_TOKEN: ${{inputs.GITHUB_TOKEN}}
    - name: Create a release
      uses: softprops/action-gh-release@v2
      with:
        body: ${{steps.github_release.outputs.changelog}}
        files: ./build-${{ inputs.platform }}-${{steps.semantic.outputs.version_tag}}.zip
        tag_name: ${{steps.semantic.outputs.version_tag}}
        name: ${{steps.semantic.outputs.version_tag}}


