name: Upload Workflow
inputs:
  platform:
    required: true
    description: "Current platform"
  AWS_KEY:
    required: true
    description: "AWS KEY"
  AWS_SECRET_KEY:
    required: true
    description: "AWS SECRET KEY"
  AWS_BUCKET:
    required: true
    description: "AWS BUCKET NAME"
  project-name:
    required: true
    description: "Project name"
  client-name:
    required: true
    description: "Client name"
  


# outputs:
#   random:
#     description: "Example output"
#     value: ${{ steps.step1.outputs.random }}

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Download Webgl Artifact
      if: ${{ inputs.platform == 'webgl' }}
      uses: actions/download-artifact@v4
      with:
        path: build-${{ inputs.platform }}-extract
    - name: Upload to S3 bucket
      if: ${{ inputs.platform == 'webgl' }}
      uses: shallwefootball/upload-s3-action@v1.2.0
      with:
          aws_key_id: ${{inputs.AWS_KEY}}
          aws_secret_access_key: ${{ inputs.AWS_SECRET_KEY }}
          aws_bucket: ${{inputs.AWS_BUCKET}}
          source_dir: build-${{ inputs.platform }}-extract
          destination_dir: ${{inputs.client-name}}/${{ inputs.project-name }}