name: Android sub pipeline
inputs:
  targetPlatform:
    required: true
    description: "Target platform"
  platform:
    required: true
    description: "Current platform"
  configFile:
    required: true
    description: "Config file"


# outputs:
#   random:
#     description: "Example output"
#     value: ${{ steps.step1.outputs.random }}

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Echo stuff
      run: |
        echo swag ${{ inputs.name }}
      shell: bash