name: Android sub pipeline
inputs:
  targetPlatform:
    required: true
    description: "Input platform"
  platform:
    required: true
    description: "Input platform"
  configFile:
    required: true
    description: "Input platform"
  

# outputs:
#   random:
#     description: "Example output"
#     value: ${{ steps.step1.outputs.random }}

runs:
  using: "composite"
  steps:
    - name: Echo stuff
      run: |
        echo swag ${{ inputs.name }}
      shell: bash